NRS with multimaps, File Containers with Registers, sequences OUT
maidsafe/sn_api pull request #833
Opened 2021-07-30 16:51 UTC by grumbach

BREAKING_CHANGE

Quite a big PR
- NRS with Multimaps
- File containers with Registers
- Removed all traces of the old Sequence CRDT

2021-08-02 05:31 UTC, davidrusu reviewed
We shouldn't always use the version's provided by the user when we are operating on registers / multi-maps, otherwise you are risk making changes to data the user had not intended to change.

Also, in your tests, you use `assert!(x != y)` in a lot, use `assert_ne!(x, y)` instead.

2021-08-02 05:31 UTC, davidrusu commented on src/app/files/mod.rs
> +            curr_serialised_files_map = m.to_owned();
```suggestion
        let (version, curr_serialised_files_map) = if let Some((v, m)) = first_entry {
            (v.into(), m.to_owned())
```

2021-08-02 05:31 UTC, davidrusu commented on src/app/files/mod.rs
> +        // We first obtain the FilesMap XOR-URL from the Sequence
```suggestion
        // We first obtain the FilesMap XOR-URL from the Register
```

2021-08-02 05:31 UTC, davidrusu commented on src/app/files/mod.rs
> +        let version = if success_count == 0 || dry_run {
On dry-run, we should return the new version hash as if the append succeeded

2021-08-02 05:31 UTC, davidrusu commented on src/app/files/mod.rs
> +                .collect();
Use `current_versions` provided by the user instead of reading the most recently updated version from the network.

2021-08-02 05:31 UTC, davidrusu commented on src/app/files/mod.rs
> +        current_version: VersionHash,
Make this be a set of VersionHash's so that we can over-write multiple concurrent versions with this one new version

2021-08-02 05:31 UTC, davidrusu commented on src/app/files/mod.rs
> +        // let's fetch version invalid version
```suggestion
        // let's fetch invalid version
```

2021-08-02 05:31 UTC, davidrusu commented on src/app/files/mod.rs
> +                let default_vh = format!("{}", VersionHash::default());
Any reason why we `format` here rather than just store the `VersionHash::default()` in the variable and format when it's needed?

2021-08-02 05:31 UTC, davidrusu commented on src/app/files/mod.rs
> +        // skip version hash check since hash didn't change on dry run
Dry-run should give back the version that would have been created

2021-08-02 05:31 UTC, davidrusu commented on src/app/nrs/mod.rs
> +            .collect();
We should be using the `version` we got above as the `old_values`.

We should always aim to operate within the context that the user is working within, this would be fetching data from the network that the user had not seen yet. We could be overwriting data that the user did not intend to overwrite.

2021-08-02 05:31 UTC, davidrusu commented on src/app/nrs/mod.rs
> +    /// ```rust_no_run
Did you intend to remove the comma here?

2021-08-02 05:31 UTC, davidrusu commented on src/app/nrs/mod.rs
> +            .collect();
Again, only operate on data that the user knows about. Use the version hash you got above for the removal.

This could remove entries that the user had not seen yet since we are doing a network fetch here.

2021-08-02 13:58 UTC, bochaco commented on src/app/files/mod.rs
> +            unimplemented!("Multiple file container entries not managed, this happends when 2 clients write concurrently to a file container");
I think it'll be better to return an error so it's properly reported to the user explaining the limitation of this lib/API, otherwise CLI (or the app using the lib) crashes and provides a dump stack trace report which users won't understand.

2021-08-02 15:53 UTC, grumbach commented on src/app/files/mod.rs
> +        let version = if success_count == 0 || dry_run {
Yes indeed but since we can't obtain a new hash because no network (register) operations are done, what should we return? We can't increment the hash like we did for u64.

2021-08-02 16:27 UTC, davidrusu commented on src/app/nrs/mod.rs
> +        // TODO use remove
Let's create an issue to track this TODO

2021-08-03 16:46 UTC, grumbach commented on src/app/files/mod.rs
> +        let version = if success_count == 0 || dry_run {
Added to TODO list when we upgrade to manage forks and DAG related conflicts

2021-08-03 16:46 UTC, grumbach commented on src/app/files/mod.rs
> +        let version = if success_count == 0 || dry_run {
Added a special unimplemented case

2021-08-03 16:49 UTC, grumbach commented on src/app/files/mod.rs
> +        current_version: VersionHash,
Will add this to the next PR when we manage DAG related conflicts, forks and resolutions

2021-08-03 16:51 UTC, grumbach commented on src/app/files/mod.rs
> +        // skip version hash check since hash didn't change on dry run
Skip that check for now (not implemented)

2021-08-04 16:57 UTC, davidrusu reviewed
Looking good, just a few more notes

2021-08-04 16:57 UTC, davidrusu commented on src/app/nrs/mod.rs
> +            return Ok((version, xorurl, processed_entries, nrs_map));
This is not the new version, return Error::Unimplemented instead

2021-08-04 16:57 UTC, davidrusu commented on src/app/nrs/mod.rs
> +            return Ok((version, xorurl, processed_entries, nrs_map));
This is not the correct version, return Unimplemented instead

2021-08-10 10:12 UTC, joshuef requested changes

2021-08-10 10:12 UTC, joshuef commented on src/app/nrs/mod.rs
> +                "No dry run for nrs_map_container_add (missing version info)".to_string(),
This error message confuses me. 

If we had versionn info, we'd do a dry run?

how come we don't have that?

2021-08-10 10:12 UTC, joshuef commented on src/app/nrs/mod.rs
> +            return Err(Error::NotImplementedError("Multiple NRS map entries not managed, this happends when 2 clients write concurrently to a NRS map".to_string()));
Let's make a real error for this as opposed to the catchall string 👍

2021-08-10 10:17 UTC, grumbach commented on src/app/nrs/mod.rs
> +                "No dry run for nrs_map_container_add (missing version info)".to_string(),
The version info is missing because register operations dry_run are not implemented yet on safe_network so there is no way currently to know the next version hash (like we use to with `u64` with a `+1`)

2021-08-10 10:20 UTC, grumbach commented on src/app/nrs/mod.rs
> +            return Err(Error::NotImplementedError("Multiple NRS map entries not managed, this happends when 2 clients write concurrently to a NRS map".to_string()));
We were thinking of implementing this in the near future, thus the `NotImplementedError` to remind us this is temporary. But I could make a real error out of it if makes things clearer, should I?

2021-08-10 10:22 UTC, grumbach commented on src/app/nrs/mod.rs
> +                "No dry run for nrs_map_container_add (missing version info)".to_string(),
Should I change the message with `register operations dry_run are not implemented yet`?

2021-08-10 10:26 UTC, joshuef commented on src/app/nrs/mod.rs
> +                "No dry run for nrs_map_container_add (missing version info)".to_string(),
```suggestion
                "No dry run for nrs_map_container_add. Version info cannot be determined. (Register operations need this funcitnoality implemented first.)".to_string(),
```

2021-08-10 10:27 UTC, joshuef commented on src/app/nrs/mod.rs
> +            return Err(Error::NotImplementedError("Multiple NRS map entries not managed, this happends when 2 clients write concurrently to a NRS map".to_string()));
This is more concrete than the above, I think it's worthwhile adding a proper error (which we can remove later), in case this does not happen "soon".

2021-08-10 10:35 UTC, grumbach commented on src/app/nrs/mod.rs
> +            return Err(Error::NotImplementedError("Multiple NRS map entries not managed, this happends when 2 clients write concurrently to a NRS map".to_string()));
```suggestion
            return Err(Error::MultimapFork("Multiple NRS map entries not managed, this happends when 2 clients write concurrently to a NRS map".to_string()));
```

2021-08-10 11:42 UTC, joshuef approved these changes

2021-08-10 11:42 UTC, merged